
export default {
  new_session: {},
  autoloader: [],
  session_name: {
    name: "session_name",
    label: "Session name",
    value: "S01",
    required: true,
  },
  group: {
    name: "group_name",
    label: "Group name",
    value: "",
    required: true,
    options: ["BaiY", "YangK", "SmothianKK"],
  },
  microscope: {
    name: "microscope",
    label: "Microscope",
    value: "",
    required: true,
    options: ["K2", "Arctica", "K34"],
  },
  detector: {
    name: "detector",
    label: "Detector",
    value: "",
    required: true,
    options: ["K2", "B3", "K4"],
  },
  // collection parameters
  atlas_x: {
    name: "atlas_x",
    label: "X coordinate of Atlas",
    value: 18,
    min: 1,
  },
  atlas_y: {
    name: "atlas_y",
    label: "Y coordinate of Atlas",
    value: 2,
    min: 1,
  },
  squares_num: {
    name: "squares_num",
    label: "Number of squares",
    value: 3,
    min: 1,
  },
  square_holes: {
    name: "square_holes",
    label: "Number of holes per square",
    value: 2,
    min: 1,
  },
  bis_max_dist: {
    name: "bis_max_dist",
    label: "Maximum distance of BIS",
    value: 3,
    min: 1,
  },
  bis_min_group_size: {
    name: "bis_min_group_size",
    label: "Minimum group size of BIS",
    value: 1,
    min: 1,
  },
  target_defocus_min: {
    name: "target_defocus_min",
    label: "Minimum target defocus",
    value: -2,
    min: -100,
  },
  target_defocus_max: {
    name: "target_defocus_max",
    label: "Maximum target defocus",
    value: -2,
    min: -100,
  },
  step_defocus: {
    name: "step_defocus",
    label: "Steop defocus",
    value: 0,
    min: -100,
  },
  drift_crit: {
    name: "drift_crit",
    label: "Drift CRIT",
    value: -1,
    min: -100,
  },
  tilt_angle: {
    name: "tilt_angle",
    label: "Tilt angle",
    value: 0,
    min: 0,
  },
  afis: {
    name: "afis",
    label: "AFIS",
    value: false,
  },
  save_frames: {
    name: "save_frames",
    label: "Save frames",
    value: true,
  },
  force_process: {
    name: "force_process",
    label: "Force Process from average",
    value: false,
  },
  offset_targeting: {
    name: "offset_targeting",
    label: "Offset targeting",
    value: true,
  },
  offset_dist: {
    name: "offset_dist",
    label: "Offset distance",
    value: -1,
    min: -100,
  },
  zeroloss_delay: {
    name: "zeroloss_delay",
    label: "Zero Loss Delay",
    value: -1,
    min: -100,
  },
  dark_delay: {
    name: "dark_delay",
    label: "Hardware dark delay",
    value: -1,
    min: -100,
  },
  multishot_per_hole_id: {
    name: "multishot_per_hole_id",
    label: "Multishot per hole ID",
    value: "",
  },
  multishot_per_hole: {
    name: "multishot_per_hole",
    label: "Multishot per hole",
    value: false,
  },
  detect_size_x: {
    name: "detect_size_x",
    label: "X coordinate of detector size",
    value: 5760,
    min: 0,
  },
  detect_size_y: {
    name: "detect_size_y",
    label: "Y coordinate of detector size",
    value: 4096,
    min: 0,
  },
  pixel_size: {
    name: "pixel_size",
    label: "Pixel size (A/pix)",
    value: 0,
    min: 0,
  },
  beam_size: {
    name: "beam_size",
    label: "Beam size (nm)",
    value: 0,
    min: 0,
  },
  hole_size: {
    name: "hole_size",
    label: "Hole size (um)",
    value: 0,
    min: 0,
  },
  max_shots: {
    name: "max_shots",
    label: "Maximum Number of shots",
    value: 2,
    min: 1,
  },
  min_field_view: {
    name: "min_field_view",
    label: "Minimum fields of views in a hole (%)",
    value: 85,
    min: 0,
    max: 100,
  },
};